### PR TITLE
set default `WebVRConfig` options in `src/main` and extend them based on user-defined `window.WebVRConfig` (fixes #49)

### LINKED ISSUE #49: Set default `WebVRConfig` options in `src/main`
Instead of having to manually look at the [`README` to see the default configuration options of `WebVRConfig`](https://github.com/borismus/webvr-polyfill#configuration), it'd be nice if the defaults were defined there and overridden by anything set by the user on `window.WebVRConfig`.

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by cvan** [comment]
issues about config changes can be addressed in this PR: #53 but keeping it there is fine. I'll fix them both up.

**Comment by borismus** [comment]
@cvan Sorry for delays, was busy with VR Views, etc. Could you revisit these conflicts so we can merge?

**Comment by cvan** [comment]
@borismus updated, thanks

**Comment by borismus** [comment]
Thanks!

**Pull request merged**
