### PR TITLE
Removed THREE.Math.degToRad dependency from gyro sensor.

### PR DESCRIPTION
**Pull request by craigsketchley**

### CODE REVIEW

**Comment by borismus** [comment]
The main THREE dependency is for Euler, Quaternion, Vector3, etc. What's the motivation behind this change?

**Comment by craigsketchley** [comment]
Sorry, thought I wrote a description. I wasn't using THREE.js in my project and the polyfill currently references `THREE.Math.degToRad` in `gyro-position-sensor-vr-device.js`. I get an exception when I try to run my project on mobile.

**Comment by borismus** [comment]
Ah, a very good point. Maybe a better approach is to patch in THREE.Math.degToRad in the same way that I do with the other THREE.* classes?

**Comment by borismus** [comment]
At any rate would appreciate if you could rebase the patch to the latest master. Thanks!

**Comment by borismus** [comment]
This has been fixed. We now pull in THREE.Math.*

**Pull request closed without merging**
