### PR TITLE
Add Edge correction world transform

### PR DESCRIPTION
**Pull request by pindiespace**
Add edge correction for world transform filter for Edge, in Windows Phone emulation mode.

### CODE REVIEW

**Comment by borismus** [comment]
Did you test this on a real Edge phone?

**Comment by pindiespace** [comment]
Nope, this is in the Edge simulator. However, Edge in Desktop mode doesn't
show the problem.

On Wed, Jan 20, 2016 at 6:14 PM, Boris Smus <notifications@github.com>
wrote:

> Did you test this on a real Edge phone?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/borismus/webvr-polyfill/pull/28#issuecomment-173428857>
> .
>



-- 
============================================================
=================
*Dr. Pete Markiewicz*
*Email:* pindiespace@gmail.com
*Sustainable virtual design blog:*
http://sustainablevirtualdesign.wordpress.com
*Sustainability template:* http://greenboilerplate.com
*Teaching site: *http://plyojump.com <http://www.plyojump.com/>
*Buy my book! *- Millennials and the Popular Culture
*Lifecourse:* http://www.lifecourse.com/store/catalog/lca/mpc.html
* AmazonAuthor Page:*
http://www.amazon.com/Pete-Markiewicz/e/B0069VZ7BG/ref=ntt_athr_dp_pel_pop_2
*On that page, see my DARPA Grand Challenge 2005 entry video, "Team
Robomonster":*
*Team Robomonster *(DARPA 2005 Grand Challenge):
http://robotsthatjump.wordpress.com/category/team-robomonster/
*Indiespace *(1st to sell downloaded music, March 1994):
http://www.indiespace.com. Also see http://archive.org under
"Kspace.com" 1996 for our original site.
============================================================
=================

**Comment by borismus** [comment]
Bizarre. Could you link to the simulator?

**Comment by pindiespace** [comment]
I'll check to see what's possible. I'm using the vanilla Edge currently
shipping with win10.

On Wed, Jan 20, 2016 at 7:32 PM, Boris Smus <notifications@github.com>
wrote:

> Bizarre. Could you link to the simulator?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/borismus/webvr-polyfill/pull/28#issuecomment-173440192>
> .
>



-- 
============================================================
=================
*Dr. Pete Markiewicz*
*Email:* pindiespace@gmail.com
*Sustainable virtual design blog:*
http://sustainablevirtualdesign.wordpress.com
*Sustainability template:* http://greenboilerplate.com
*Teaching site: *http://plyojump.com <http://www.plyojump.com/>
*Buy my book! *- Millennials and the Popular Culture
*Lifecourse:* http://www.lifecourse.com/store/catalog/lca/mpc.html
* AmazonAuthor Page:*
http://www.amazon.com/Pete-Markiewicz/e/B0069VZ7BG/ref=ntt_athr_dp_pel_pop_2
*On that page, see my DARPA Grand Challenge 2005 entry video, "Team
Robomonster":*
*Team Robomonster *(DARPA 2005 Grand Challenge):
http://robotsthatjump.wordpress.com/category/team-robomonster/
*Indiespace *(1st to sell downloaded music, March 1994):
http://www.indiespace.com. Also see http://archive.org under
"Kspace.com" 1996 for our original site.
============================================================
=================

**Comment by borismus** [comment]
Thanks. If we're patching Edge support, it's important to test on a real phone.

**Comment by borismus** [comment]
Closing until this is actually tested on a real device.

**Comment by pindiespace** [comment]
Yup, they're hard to find!

**Pull request closed without merging**
